# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: apps
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./apps/staging
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/tclutin/apps-repo.git
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: podinfo
  releaseName: podinfo
  interval: 10m
  chart:
    spec:
      chart: ./podinfo
      sourceRef:
        kind: GitRepository
        name: apps-repo
  values:
    replicaCount: 1
