apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: podinfo
  url: https://github.com/tclutin/apps-repo.git